- debug: msg="IN THE CLONE FILE"

- name: ensure atmosphere location
  command: mkdir -p {{ ATMOSPHERE_LOCATION }}

- name: clone atmosphere git repo
  git: repo=https://github.com/iPlantCollaborativeOpenSource/atmosphere.git
       dest={{ ATMOSPHERE_LOCATION }}
       clone=yes
       update=yes
  when: ATMOSPHERE_BRANCH |length == 0  

- name: clone atmosphere git repo with branched defined
  git: repo=https://github.com/iPlantCollaborativeOpenSource/atmosphere.git
       dest={{ ATMOSPHERE_LOCATION }}
       clone=yes
       update=yes
       version={{ ATMOSPHERE_BRANCH | default("master") }}
  when: ATMOSPHERE_BRANCH |length > 0

- name: clone atmosphere git repo
  git: repo=https://github.com/iPlantCollaborativeOpenSource/atmosphere.git
       dest=/tmp/atmosphere
       clone=yes
       update=yes
  when: ATMOSPHERE_BRANCH |length == 0  

- name: clone atmosphere git repo with branched defined
  git: repo=https://github.com/iPlantCollaborativeOpenSource/atmosphere.git
       dest=/tmp/atmosphere
       clone=yes
       update=yes
       version={{ ATMOSPHERE_BRANCH | default("master") }}
  when: ATMOSPHERE_BRANCH |length > 0
