- name: ensure atmosphere location
  file: path={{ ATMOSPHERE_LOCATION }} state=directory

- name: clone atmosphere git repo
  git: repo={{ ATMOSPHERE_REPO }}
       dest={{ ATMOSPHERE_LOCATION }}
       clone=yes
       update=yes
  when: ATMOSPHERE_BRANCH |length == 0  

- name: clone atmosphere git repo with branched defined
  git: repo={{ ATMOSPHERE_REPO }}
       dest={{ ATMOSPHERE_LOCATION }}
       clone=yes
       update=yes
       version={{ ATMOSPHERE_BRANCH | default("master") }}
  when: ATMOSPHERE_BRANCH |length > 0

##### Ansible Roles bioci 
- name: ensure ansible role location
  file: path={{ ANSIBLE_DEPLOY_LOCATION }} state=directory

- name: clone ansible git repo
  git: repo={{ ANSIBLE_REPO }}
       dest={{ ANSIBLE_DEPLOY_LOCATION }}
       clone=yes
       update=yes
       force=yes
       version="master"
  tags:
    - ansible-deploy
