- name: pull atmosphere git repo with branched not defined
  git: repo={{ ATMOSPHERE_REPO }}
       dest={{ ATMOSPHERE_LOCATION }}
       clone=no
       update=yes
       force=yes
       version="master"
  when: ATMOSPHERE_BRANCH |length == 0

- name: pull atmosphere git repo with branched defined
  git: repo={{ ATMOSPHERE_REPO }}
       dest={{ ATMOSPHERE_LOCATION }}
       clone=no
       update=yes
       force=yes
       version={{ ATMOSPHERE_BRANCH | default("master") }}
  when: ATMOSPHERE_BRANCH |length > 0

- name: pull atmosphere ansible git repo
  git: repo={{ ANSIBLE_REPO }}
       dest={{ ANSIBLE_DEPLOY_LOCATION }}
       clone=yes
       update=yes
       force=yes
       version="master"
  tags:
    - ansible-deploy
