- name: pull atmosphere git repo with branched not defined
  git: repo=https://github.com/iPlantCollaborativeOpenSource/atmosphere.git
       dest={{ ATMOSPHERE_LOCATION }}
       clone=no
       update=yes
       force=yes
       version="master"
  when: ATMOSPHERE_BRANCH |length == 0

- name: pull atmosphere git repo with branched defined
  git: repo=https://github.com/iPlantCollaborativeOpenSource/atmosphere.git
       dest={{ ATMOSPHERE_LOCATION }}
       clone=no
       update=yes
       force=yes
       version={{ ATMOSPHERE_BRANCH | default("master") }}
  when: ATMOSPHERE_BRANCH |length > 0
