---
  # use the new container infrastructure
  sudo: required
  dist: trusty

  langauge: python
  python: "2.7"

  addons:
  postgresql: "9.6"

  before_install:
    - sudo apt-get update
    - sudo apt-get install -y git python python-pip python-dev libffi-dev libssl-dev software-properties-common python-software-properties
    - sudo apt-get purge --auto-remove redis-server
    - sudo pg_dropcluster --stop 9.1 main
    - sudo pg_dropcluster --stop 9.2 main
    - sudo pg_dropcluster --stop 9.3 main
    - sudo pg_dropcluster --stop 9.4 main
    - sudo pg_dropcluster --stop 9.5 main
    - sudo pg_dropcluster --stop 9.9 main
    - sudo service postgresql start 9.6
    - sudo pg_lsclusters

  before_script:
    - virtualenv clank_env
    - . clank_env/bin/activate
    - pip install -r requirements.txt
    - cp dist_files/variables.yml.dist variables.yml

  script:
    - clank_env/bin/python ./clank.py --env_file variables.yml -b --skip-tags "distro-update,create-nginx-uwsgi"
