---
  # use the new container infrastructure
  sudo: required
  dist: trusty

  langauge: python
  python: "2.7"  

  before_install:
    - sudo apt-get update
    - sudo apt-get install -y git python python-pip python-dev libffi-dev libssl-dev


  before_script:
    - virtualenv clank_env
    - . clank_env/bin/activate
    - pip install -r requirements.txt
    - cp dist_files/variables.yml.dist variables.yml

  script:
    - clank_env/bin/python ./clank.py --env_file variables.yml --tags install-dependencies
