---

- debug: var=UWSGI_INI_SRC_NAME
  when: DEBUG_OR_TEST_ROLE | default(False)

- name: create apps-enabled directory
  file: path={{ UWSGI_APPS_ENABLED_PATH }} state=directory

- name: link {{ UWSGI_APP_NAME | default('') }} uwsgi conf file
  file: src={{ UWSGI_APP_SRC }} dest={{ UWSGI_APP_DEST }} state=link
  tags:
    - deploy

- block:
    - name: Link uwsgi.service systemd file to /etc/systemd
      file:
        src: "{{ APP_BASE_DIR }}/extras/systemd/uwsgi.service"
        dest: "/etc/systemd/system/uwsgi.service"
        state: link

    - name: Comment out 'socket' line of default uwsgi ini
      lineinfile:
        path: /usr/share/uwsgi/conf/default.ini
        regexp: "^socket ="
        line: "#socket = /run/uwsgi/%(deb-confnamespace)/%(deb-confname)/socket"
        state: present
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "16") or (ansible_distribution == "CentOS" and ansible_distribution_major_version >= "7")

- name: make nginx configuration files
  shell: make
  args:
    chdir: "{{ APP_BASE_DIR }}/extras/nginx"
  register: output
  tags:
    - deploy

- debug: var=output.stdout_lines
  when: CLANK_VERBOSE | default(False)
