---
# tasks file for app-backup-postgres

- name: Create "backups" directory
  file:
    path: "{{ BACKUP_PATH }}/{{ ansible_date_time.date }}/{{ item.PROJECT_NAME }}"
    state: directory
    mode: 0770
  with_items: LIST_OF_BACKUPS
    
  # The following task is helpful for copying the backup directory to a location that the postgresql user normally can't copy to
- name: Copy backup to specific location
  command: cp -r {{ item.1 }} {{ BACKUP_PATH }}/{{ ansible_date_time.date }}/{{ item.0.PROJECT_NAME }}
  with_subelements:
    - LIST_OF_BACKUPS
    - FILES
