---
- name: Include atmosphere in the startup process
  block:
    - name: Install atmosphere init.d script
      copy:
        src: "{{ role_path }}/files/atmosphere"
        dest: /etc/init.d/atmosphere
        mode: 0755

    - name: Install atmosphere init.d script
      service:
        name: atmosphere
        enabled: yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version < "16"
