---
# tasks file for atmosphere-include-startup
- name: Include atmosphere in the startup process
  service:
    name: 'atmosphere'
    enabled: 'yes'
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version < "16"
  tags: enable-services
