- name: create troposphere directory
  file: path={{ TROPOSPHERE_DIR }} state=directory

- name: check to see if repo exists
  stat: path={{ TROPOSPHERE_LOCATION }}/.git
  register: p

# include clone.yml when the repo does not exist
- include: clone.yml
  when: p.stat.exists == false

# include pull.yml when the repo does exists
- include: pull.yml
  when: p.stat.exists
