- name: pip install requirements
  pip: requirements={{ TROPOSPHERE_LOCATION }}/requirements.txt virtualenv={{ VIRTUAL_ENV_TROPOSPHERE }}

- name: create troposphere log directory
  command: mkdir -p {{ TROPOSPHERE_LOCATION }}/logs

- name: move over precompleted variables.ini
  copy: src=troposphere_variables.ini dest={{ TROPOSPHERE_LOCATION }}/variables.ini

- name: run generate scripts for troposphere
  shell: "{{ VIRTUAL_ENV_ATMOSPHERE }}/bin/python {{ TROPOSPHERE_LOCATION }}/scripts/generate_configs.py" 

#### TODO the Make file needs to be a template or something to insert variables

#- name: Build troposphere
#  shell: 'cd {{ TROPOSPHERE_LOCATION }}; {{ item }}'
#  with_items:
#    - make
#    #- npm install
#    #- npm run build

- name: add webserver user for user and group permissions
  file: path={{ TROPOSPHERE_LOCATION }} owner={{ WEBSERVER_USER }} group={{ WEBSERVER_USER }} recurse=yes
