- name: pip install requirements
  pip: requirements={{ TROPOSPHERE_LOCATION }}/requirements.txt virtualenv={{ VIRTUAL_ENV_TROPOSPHERE }}

- name: create troposphere log directory
  command: mkdir -p {{ TROPOSPHERE_LOCATION }}/logs

- name: move over precompleted variables.ini
  copy: src=troposphere_variables.ini dest={{ TROPOSPHERE_LOCATION }}/variables.ini

- name: run generate scripts for troposphere
  shell: "{{ VIRTUAL_ENV_ATMOSPHERE }}/bin/python {{ TROPOSPHERE_LOCATION }}/scripts/generate_configs.py" 

- name: add webserver user for user and group permissions
  file: path={{ TROPOSPHERE_LOCATION }} owner={{ WEBSERVER_USER }} group={{ WEBSERVER_USER }} recurse=yes

- name: Build troposphere
  shell: '{{ item }}'
  args:
    chdir: "{{ TROPOSPHERE_LOCATION }}"
  with_items:
    - make
#    - npm install
#    - npm run build

# nginx portion
- name: create apps-enabled directory
  command: mkdir -p {{ UWISGI_APPS_ENABLED_PATH }}

- name: link troposphere uwisgi conf file
  file: src={{ TROPOSPHERE_LOCATION }}/extras/troposphere.uwsgi.ini dest={{ UWISGI_APPS_ENABLED_PATH }}/troposphere.ini state=link

- name: make uwisgi and nginx stuff
  shell: '{{ item }}'
  args:
    chdir: "{{ TROPOSPHERE_LOCATION }}/extras/nginx"
  with_items:
    - make  
