- name: pip install requirements
  pip: requirements={{ TROPOSPHERE_LOCATION }}/requirements.txt virtualenv={{ VIRTUAL_ENV_TROPOSPHERE }}

- name: create troposphere log directory
  command: mkdir -p {{ TROPOSPHERE_LOCATION }}/logs

#### TODO move other troposphere templates when Evan is finished creating them
- name: move over local.py template
  template: src=/tmp/troposphere/troposphere/settings/local.py.j2 dest={{ TROPOSPHERE_LOCATION }}/troposphere/settings/local.py





#### TODO the Make file needs to be a template or something to insert variables

#- name: Build troposphere
#  shell: 'cd {{ TROPOSPHERE_LOCATION }}; {{ item }}'
#  with_items:
#    - make
#    #- npm install
#    #- npm run build

- name: add webserver user for user and group permissions
  file: path={{ TROPOSPHERE_LOCATION }} owner={{ WEBSERVER_USER }} group={{ WEBSERVER_USER }} recurse=yes
