---
# defaults file for app-backup-postgres

BACKUP_PATH: /root/atmo_backups

LIST_OF_BACKUPS:
    # Copy out Atmosphere specific confs
  - NAME: atmosphere
    PROJECT_NAME: atmo
    FILES:
        - /opt/dev/atmosphere/variables.ini
        - /opt/dev/atmosphere/atmosphere/settings/local.py
        - /opt/dev/atmosphere/atmosphere/settings/secrets.py
   
    # Copy out troposphere specific conf
  - NAME: troposphere
    PROJECT_NAME: tropo
    FILES:
      - /opt/dev/troposphere/variables.ini
      - /opt/dev/troposphere/package.json
      - /opt/dev/troposphere/troposphere/settings/local.py

    # Copy out nginx/uswgi confs
  - NAME: web_confs
    PROJECT_NAME: web_confs
    FILES:
      - /etc/nginx/sites-enabled
      - /etc/nginx/locations
      - /etc/uwsgi/apps-enabled
      - /etc/default/celeryd
