---
# tasks file for app-install-instance-deploy-automation
# Installation is *NOT* complete until the app-generate-ini role

- name: move over completed hosts file
  copy: >
    src={{ INSTANCE_DEPLOY_AUTOMATION_HOSTS_FILE }}
    dest={{ INSTANCE_DEPLOY_AUTOMATION_DIR }}/ansible

- name: move over completed group_vars folder
  copy: >
    src={{ INSTANCE_DEPLOY_AUTOMATION_GROUP_VARS_FOLDER }}
    dest={{ INSTANCE_DEPLOY_AUTOMATION_DIR }}/ansible
