---
# tasks file for app-install-instance-deploy-automation

- name: run configuration for atmosphere-ansible
  shell: "{{ VIRTUAL_ENV_ATMOSPHERE }}/bin/python {{ INSTANCE_DEPLOY_AUTOMATION_DIR }}/configure"
  failed_when: False
  register: output

- debug: var=output.stdout_lines
  when: "{{ CLANK_VERBOSE | default(False) }}"

- name: move over completed hosts file
  copy: >
    src={{ INSTANCE_DEPLOY_AUTOMATION_HOSTS_FILE }}
    dest={{ INSTANCE_DEPLOY_AUTOMATION_DIR }}/ansible

- name: move over completed group_vars folder
  copy: >
    src={{ INSTANCE_DEPLOY_AUTOMATION_GROUP_VARS_FOLDER }}
    dest={{ INSTANCE_DEPLOY_AUTOMATION_DIR }}/ansible
