- name: gather variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"
  tags: 
    - vars
    - postgres

- name: insert/update "Database User" configuation block in /etc/postgresql/{{ DB_VERSION }}/main/pg_hba.conf
  blockinfile:
    dest: "/etc/postgresql/{{ DB_VERSION }}/main/pg_hba.conf"
    block: |
      local   all              {{ item }}                  md5
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{item}}"
  with_items:
      - "{{ DBUSER }}"
    
- name: PostgreSQL - Ensure PostgreSQL is running
  service: name=postgresql state=started args={{ DB_VERSION }}
  tags:
    - postgres
