# We must remove the line that we want to insert, otherwise ansible will not
# respect "insertbefore". It's only respected when inserting lines that don't
# already exist, so if you want to insert a line, you must remove it first.
#
# https://github.com/ansible/ansible/issues/21176#issuecomment-278557219
#
- block:
    - name: "Explicitly remove database user, to ensure inserting in the right location"
      lineinfile:
          dest: "/etc/postgresql/{{ DB_VERSION }}/main/pg_hba.conf"
          regexp: "^local +all +{{ DBUSER }} +md5"
          state: absent

    - name: "Give database user ({{ DBUSER }}) password authentication on domain sockets"
      lineinfile:
        dest: "/etc/postgresql/{{ DB_VERSION }}/main/pg_hba.conf"

        # Note: We must insert 'line' before this more restrictive line, if it exists.
        insertbefore: "^local +all +all +peer"

        line: "local   all              {{ DBUSER }}                  md5"

  tags:
    - postgres

- name: Restart postgres to reload configuration
  service: name=postgresql state=restarted args={{ DB_VERSION }}
  tags:
    - postgres
