---
# tasks file for noc-enable-new-relic
- block:

  - fail: msg="Wait! Variable TARGET_HOME must be set."
    when: TARGET_HOME == ""

  - fail: msg="Wait! Variable MODULE_NAME must be set."
    when: MODULE_NAME == ""

  - stat: path="{{ TARGET_HOME }}/{{ MODULE_NAME }}/{{ LOCAL_SETTINGS }}"
    register: settings_path

  - fail: msg="Wait! {{ TARGET_HOME }}/{{ MODULE_NAME }}/{{ LOCAL_SETTINGS }} should exist"
    when: settings_path.stat.exists == False

  - name: ensure role has local files directory
    local_action: >
        file path={{ role_path }}/files state=directory mode=0755

  - name: ensure new_relic settings file exists
    file:
      path: "{{ TARGET_HOME }}/{{ MODULE_NAME }}/{{ NEW_RELIC_SETTINGS }}"
      state: touch
      mode: 0644

  - name: ensure new_relic extras directory exists
    file:
      path: "{{ TARGET_HOME }}/{{ NEW_RELIC_EXTRAS }}"
      state: directory
      mode: 0755

  - name: Add New Relic settings to '{{ MODULE_NAME }}/{{ NEW_RELIC_SETTINGS }} (if browser is False)'
    blockinfile:
      dest: "{{ TARGET_HOME }}/{{ MODULE_NAME }}/{{ NEW_RELIC_SETTINGS }}"
      block: |
        NEW_RELIC_ENVIRONMENT = '{{ NEW_RELIC.ENVIRONMENT }}'
      marker: "# {mark} ANSIBLE MANAGED BLOCK "
    when: settings_path.stat.exists and new_relic_browser == False

  - name: Add New Relic settings to '{{ MODULE_NAME }}/{{ NEW_RELIC_SETTINGS }} (if browser is True)'
    blockinfile:
      dest: "{{ TARGET_HOME }}/{{ MODULE_NAME }}/{{ NEW_RELIC_SETTINGS }}"
      block: |
        NEW_RELIC_ENVIRONMENT = '{{ NEW_RELIC.ENVIRONMENT }}'
        NEW_RELIC_BROWSER_SNIPPET = '{{ NEW_RELIC.BROWSER }}'
      marker: "# {mark} ANSIBLE MANAGED BLOCK "
    when: settings_path.stat.exists and new_relic_browser

  - name: Templated app_newrelic.ini to newrelic.ini
    template:
      src: "{{ role_path }}/templates/app_newrelic.ini.j2"
      dest: "{{ TARGET_HOME }}/{{ NEW_RELIC_EXTRAS }}/{{MODULE_NAME}}_newrelic.ini"

  when: NEW_RELIC is defined
