- name: clone git repo with branched defined
  git:
    repo: "{{ REPO_URI }}"
    dest: "{{ CLONE_TARGET }}"
    clone: yes
    depth: 1
    update: yes
    version: "{{ SPECIFIC_BRANCH | default('master', true) }}"
