- name: "Clone git repo {{ REPO_URI }} with branch {{ branch }}"
  git:
    repo: "{{ REPO_URI }}"
    dest: "{{ CLONE_TARGET }}"
    remote: "{{ REMOTE_TARGET }}"
    clone: yes
    depth: "{%- if shallow_clone -%}1{%- else -%}0{%- endif -%}"
    update: yes
    version: "{{ branch }}"
  vars:
    branch: "{{ SPECIFIC_BRANCH | default('master', true) }}"
