- name: clone git repo with branched defined
  git:
    repo: "{{ REPO_URI }}"
    dest: "{{ CLONE_TARGET }}"
    clone: yes
    depth: "{{ GIT_CLONE_DEPTH | default(1) }}"
    update: yes
    version: "{{ SPECIFIC_BRANCH | default('master', true) }}"
