- name: create atmosphere directory
  command: mkdir -p "{{ DEPLOY_DIR }}"
  tags:
    - ansible-deploy

- name: check to see if repo exists
  stat: path={{ LOCATION }}/.git
  register: p
  tags:
    - ansible-deploy

- name: clone atmosphere git repo with branched defined
  git: repo={{ REPO }}
       dest={{ LOCATION }}
       clone=yes
       update=yes
       version={{ BRANCH | default("master", true) }}
  when: p.stat.exists == false

- name: pull git repo with branched
  git: repo={{ REPO }}
       dest={{ LOCATION }}
       clone=no
       update=yes
       force=yes
       version={{ BRANCH | default("master", true) }}
  when: p.stat.exists
