# tasks to install LDAP
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"
  tags: vars

- name: include move ssl script when variables are defined
  include: move_ssl.yml
  when: CREATE_SSL != true

- name: include create ssl scripts when variables are undefined
  include: create_ssl.yml
  when: CREATE_SSL == true
