- name: copy over ssl certificate
  copy: src={{ SSL_CERTIFICATE }} dest={{ SSL_LOCATION }}/certs/

- name: copy over bundle cert
  copy: src={{ BUNDLE_CERT }} dest={{ SSL_LOCATION }}/certs/

- name: copy over private ssl key
  copy: src={{ SSL_KEY }} dest={{ SSL_LOCATION }}/private/
