- name: include main.yml file
  include_vars: main.yml

- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: vars

- name: include apache vars file if webserver is set to it
  include_vars: apache.yml
  when: WEBSERVER == "apache"

- name: include apache setup files if webserver is set to it
  include: apache.yml
  when: WEBSERVER == "apache"

- name: include nginx vars file if webserver is set to it
  include_vars: nginx.yml
  when: WEBSERVER == "ngnix"

- name: include niginx setups files if webserver is set to it
  include: nginx.yml
  when: WEBSERVER == "ngnix"
