- name: Creating self-signed server SSL cert
  command: >
    openssl req -new
      -x509
      -nodes
      -extensions v3_ca
      -days {{ item.days|default(3650) }}
      -subj "/C={{ item.country|default('') }}/ST={{ item.state|default('') }}/L={{ item.city|default('') }}/O={{ item.organization|default('') }}/OU={{ item.unit|default('') }}{% if item.domains is defined %}{% for domain in item.domains %}/CN={{ domain }}{% endfor %}{% else %}/CN={{ item.name }}{% endif %}/emailAddress={{ item.email|default('') }}"
      -keyout {{ SSL_LOCATION }}/private/{{ item.name }}.key
      -out {{ SSL_LOCATION }}/certs/{{ item.name }}.crt
  args:
    creates: "{{ SSL_CERTIFICATE }}/certs/{{ item.name }}.crt"
  with_items: OPENSSL_SELF_SIGNED
