APT_REPOSITORIES_TO_REMOVE:
  packages:
    - ppa:chris-lea/node.js
  state: absent

APT_KEYS_TO_ADD:
  packages:
    - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  state: present

APT_REPOSITORIES_TO_ADD:
  packages:
    - ppa:nginx/stable
    - deb https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main
    - ppa:chris-lea/redis-server
  state: present

INITIAL_PACKAGES:
  packages:
    - software-properties-common
    - python-software-properties
  state: latest

DEV_PACKAGES:
  packages:
    - libffi-dev
    - python
    - openssl
    - g++
    - make
    - build-essential
    - postgresql
    - postgresql-contrib
    - python-psycopg2
    - postgresql-server-dev-all
    - libpq-dev
    - python-dev
    - libldap2-dev
    - libsasl2-dev
    - python-m2crypto
    - swig
    - redis-server
    - libssl-dev
    - git
    - nodejs
    - ruby1.9.1
    - python-pip
    - python-setuptools
    - ufw
  state: latest

LIB_PACKAGES:
  packages:
    - libxml2-dev
    - libxslt1-dev
    - python-tk
    - zlib1g-dev
  state: latest

NGINX_PACKAGES:
  packages:
    - uwsgi
    - uwsgi-plugin-python
    - nginx-full
  state: latest

APACHE: apache2


