SSL_LOCATION: /etc/ssl/

SSL_CERTIFICATE: ""
SSL_KEY:

KIBANA_URL: https://download.elastic.co/kibana/kibana/kibana
KIBANA_VERSION: 4.2.0
KIBANA_OS: linux
KIBANA_ARCH: x64
KIBANA_DIR: /opt

SERVICE_INIT: /etc/init.d
SERVICE_DEFAULT: /etc/default

INIT_URL: https://gist.githubusercontent.com/thisismitch/8b15ac909aed214ad04a/raw/fc5025c3fc499ad8262aff34ba7fde8c87ead7c0/kibana-4.x-init
DEFAULT_URL: https://gist.githubusercontent.com/thisismitch/8b15ac909aed214ad04a/raw/fc5025c3fc499ad8262aff34ba7fde8c87ead7c0/kibana-4.x-default

KIBANA_USER: kibanaadmin
