- name: pip install requirements
  pip: requirements={{ ATMOSPHERE_LOCATION }}/requirements.txt virtualenv={{ VIRTUAL_ENV_ATMOSPHERE }}

- name: wheel install requirements
  command: "{{ VIRTUAL_ENV_ATMOSPHERE }}/bin/wheel install-scripts celery"

- name: move over local.py template
  template: src=local.py.j2 dest={{ ATMOSPHERE_LOCATION }}/atmosphere/settings/local.py

- name: mover over secrets.py template
  template: src=secrets.py.j2 dest={{ ATMOSPHERE_LOCATION }}/atmosphere/settings/secrets.py
