- name: pip install requirements
  pip: requirements={{ ATMOSPHERE_LOCATION }}/requirements.txt virtualenv={{ VIRTUAL_ENV_ATMOSPHERE }}

- name: wheel install requirements
  command: "{{ VIRTUAL_ENV_ATMOSPHERE }}/bin/wheel install-scripts celery"

- name: move over local.py template
  template: src=local.py.j2 dest={{ ATMOSPHERE_LOCATION }}/atmosphere/settings/local.py

- name: move over secrets.py template
  template: src=secrets.py.j2 dest={{ ATMOSPHERE_LOCATION }}/atmosphere/settings/secrets.py

- name: move over wsgi.py template
  template: src=wsgi.py.j2 dest={{ ATMOSPHERE_LOCATION }}/atmosphere/wsgi.py force=yes

- name: make ssh file directory
  command: mkdir -p {{ ATMOSPHERE_LOCATION }}/extras/ssh/

- name: move over id_rsa private key
  copy: src=id_rsa dest={{ ATMOSPHERE_LOCATION }}/extras/ssh/

- name: move over id_rsa public key
  copy: src=id_rsa.pub dest={{ ATMOSPHERE_LOCATION }}/extras/ssh/

- name: create atmosphere log directory
  command: mkdir -p {{ ATMOSPHERE_LOCATION }}/logs

- name: touch atmosphere.log
  command: touch {{ ATMOSPHERE_LOCATION }}/logs/atmosphere.log

- name: touch atmosphere_status.log
  command: touch {{ ATMOSPHERE_LOCATION }}/logs/atmosphere_status.log

- name: add webserver user for user and group permissions
  file: path={{ ATMOSPHERE_LOCATION }} owner={{ WEBSERVER_USER }} group={{ WEBSERVER_USER }} recurse=yes
