- name: copy over atmosphere sql scripts for postgresql to run
  copy: src={{ ATMOSPHERE_DATABASE_FILE_TO_BE_LOADED }} dest={{ POSTGRES_SQL_INSTALL_DIRECTORY }}
  when: LOAD_ATMOSPHERE_DATABASE

- name: run atmosphere sql scripts for postgresql
  sudo_user: postgres
  command: psql -f {{ POSTGRES_SQL_INSTALL_DIRECTORY }}/{{ ATMOSPHERE_DATABASE_FILE_TO_BE_LOADED | basename }} 
  when: LOAD_ATMOSPHERE_DATABASE

- name: pip install requirements
  pip: requirements={{ ATMOSPHERE_LOCATION }}/requirements.txt virtualenv={{ VIRTUAL_ENV_ATMOSPHERE }}

- name: pip install dev requirements when jenkins variable set
  pip: requirements={{ ATMOSPHERE_LOCATION }}/dev_requirements.txt virtualenv={{ VIRTUAL_ENV_ATMOSPHERE }}
  when: JENKINS

- name: wheel install requirements
  command: "{{ VIRTUAL_ENV_ATMOSPHERE }}/bin/wheel install-scripts celery"

- name: insert ansible role path into config file
  lineinfile: dest={{ ANSIBLE_DEPLOY_LOCATION }}/ansible/ansible.cfg regexp="roles_path =" line="roles_path = {{ ANSIBLE_DEPLOY_LOCATION }}/ansible/roles"
  tags:
    - ansible-deploy

- name: ensure local files directory exists
  local_action: >
      file path={{ role_path }}/files state=directory mode=0755

- name: create local atmosphere_variables.ini from dist
  local_action: >
      template src=../../../dist_files/atmosphere_variables.ini.j2 dest={{ role_path }}/files/atmosphere_variables.ini
 
- name: move over precompleted variables.ini
  copy: src=atmosphere_variables.ini dest={{ ATMOSPHERE_LOCATION }}/variables.ini backup=yes

- name: run generate scripts for atmosphere
  shell: "{{ VIRTUAL_ENV_ATMOSPHERE }}/bin/python {{ ATMOSPHERE_LOCATION }}/configure"

- name: make ssh file directory
  command: mkdir -p {{ ATMOSPHERE_LOCATION }}/extras/ssh/

- name: move over id_rsa private key
  copy: src={{ ID_RSA }} dest={{ ATMOSPHERE_LOCATION }}/extras/ssh/

- name: move over id_rsa public key
  copy: src={{ ID_RSA_PUB }} dest={{ ATMOSPHERE_LOCATION }}/extras/ssh/

- name: make sure ssh config exists
  file: path=/root/.ssh/config state=touch

- name: move over completed hosts file
  copy: src={{ ANSIBLE_HOSTS_FILE }} dest={{ ANSIBLE_DEPLOY_LOCATION }}/ansible

- name: move over completed group_vars folder
  copy: src={{ ANSIBLE_GROUP_VARS_FOLDER }} dest={{ ANSIBLE_DEPLOY_LOCATION }}/ansible

- name: add IdentityFile line to system's ssh config
  lineinfile: dest=/root/.ssh/config state=present create=yes line='IdentityFile {{ ATMOSPHERE_LOCATION }}/extras/ssh/{{ ID_RSA | basename }}' insertbefore=BOF

- name: add IdentityFile line to system's ssh config
  lineinfile: dest=/root/.ssh/config state=present create=yes line='IdentityFile /root/.ssh/id_rsa' insertbefore=BOF

- name: add strict no hostkey checking
  lineinfile: dest=/root/.ssh/config insertafter=EOF line="Host *\n      StrictHostKeyChecking no"

- name: create atmosphere log directory
  command: mkdir -p {{ ATMOSPHERE_LOCATION }}/logs

#### DB migrations

- name: atmosphere manage migrate
  django_manage: >
      command=migrate
      app_path={{ ATMOSPHERE_LOCATION }}
      settings='atmosphere.settings'
      pythonpath={{ ATMOSPHERE_LOCATION }}
      virtualenv={{ VIRTUAL_ENV_ATMOSPHERE }}

- name: atmosphere manage load provider fixtures
  django_manage: >
      command=loaddata
      app_path={{ ATMOSPHERE_LOCATION }}
      fixtures={{ ATMOSPHERE_LOCATION }}/core/fixtures/provider.json
      settings='atmosphere.settings'
      pythonpath={{ ATMOSPHERE_LOCATION }}
      virtualenv={{ VIRTUAL_ENV_ATMOSPHERE }}

- name: atmosphere manage load quota fixtures
  django_manage: >
      command=loaddata
      app_path={{ ATMOSPHERE_LOCATION }}
      fixtures={{ ATMOSPHERE_LOCATION }}/core/fixtures/quota.json
      settings='atmosphere.settings'
      pythonpath={{ ATMOSPHERE_LOCATION }}
      virtualenv={{ VIRTUAL_ENV_ATMOSPHERE }}

- name: atmosphere manage created atmosphere cache requests table
  django_manage: >
      command=createcachetable
      cache_table="atmosphere_cache_requests"
      app_path={{ ATMOSPHERE_LOCATION }}
      settings='atmosphere.settings'
      pythonpath={{ ATMOSPHERE_LOCATION }}
      virtualenv={{ VIRTUAL_ENV_ATMOSPHERE }}

- name: atmosphere manage collectstatic
  django_manage: >
      command=collectstatic
      app_path={{ ATMOSPHERE_LOCATION }}
      settings='atmosphere.settings'
      pythonpath={{ ATMOSPHERE_LOCATION }}
      virtualenv={{ VIRTUAL_ENV_ATMOSPHERE }}

- name: touch atmosphere.log
  command: touch {{ ATMOSPHERE_LOCATION }}/logs/atmosphere.log

- name: touch atmosphere_status.log
  command: touch {{ ATMOSPHERE_LOCATION }}/logs/atmosphere_status.log

- name: add webserver user for user and group permissions
  file: path={{ ATMOSPHERE_LOCATION }} owner={{ WEBSERVER_USER }} group={{ WEBSERVER_USER }} recurse=yes

# nginx portion
- name: create apps-enabled directory 
  command: mkdir -p {{ UWISGI_APPS_ENABLED_PATH }}

- name: make uwisgi and nginx stuff
  shell: "{{ item }}"
  args:
    chdir: "{{ ATMOSPHERE_LOCATION }}/extras/nginx"  
  with_items:
    - make

- name: link uwsgi atmosphere.ini file
  file: src={{ ATMOSPHERE_LOCATION }}/extras/uwsgi/atmo.uwsgi.ini dest={{ UWISGI_APPS_ENABLED_PATH }}/atmosphere.ini state=link
