---
- name: Remove node modules
  file: path={{ NPM_APP_DIR }}/node_modules state=absent
  when: NPM_CLEAN_BUILD

- name: run npm install
  command: npm install --unsafe-perm
  args:
    chdir: "{{ NPM_APP_DIR }}"
  register: result

- name: Log output of npm install
  debug: var=result.stdout_lines

- name: Run npm build
  command: npm run build --{{ NPM_BUILD_TYPE | default("production")}}
  args:
    chdir: "{{ NPM_APP_DIR }}"
  register: result

- name: Log output of npm build
  debug: var=result.stdout_lines
