---
- name: Playbook to run the neccessary roles to build atmosphere
  hosts: all
  roles:
    # Atmosphere Portion
    - atmosphere-setup-virtualenv
    - atmosphere-clone-repo
    - atmosphere-setup-atmosphere
    - setup-celery
