---
- name: Playbook to install and configure atmosphere and troposphere
  hosts: all
  roles:
    # Dependencies
    - { role: install-dependencies, tags: [ 'dependencies', 'packages'] }
    - { role: setup-postgres, tags: [ 'dependencies', 'db'] }
    - { role: setup-ssl, tags: [ 'dependencies', 'ssl'] }

    # Atmosphere Portion
    - { role: atmosphere-setup-virtualenv, tags: [ 'atmosphere', 'setup-virtualenv'] }
    - { role: atmosphere-clone-repo, tags: [ 'atmosphere', 'clone-repo'] }
    - { role: atmosphere-setup-atmosphere, template_vars: "{{ ATMO }}",
        tags: [ 'atmosphere', 'setup-atmosphere'] }
    - { role: setup-celery , tags: [ 'atmosphere', 'celery'] }

    # Troposphere Portion
    - { role: troposphere-setup-virtualenv, tags: [ 'troposphere', 'setup-virtualenv'] }
    - { role: troposphere-clone-repo, tags: [ 'troposphere', 'clone-repo'] }
    - { role: troposphere-setup-troposphere, template_vars: "{{ TROPO }}",
        tags: [ 'troposphere', 'setup-troposphere'] }
