---
- name: Playbook to install and configure troposphere
  hosts: all
  roles:
    - install-dependencies
    - troposphere-setup-virtualenv
    #- atmosphere-setup-postgres
    #- troposphere-setup-virtualenv
    #- atmosphere-clone-repo
    #- atmosphere-setup-atmosphere
    #- atmosphere-setup-ssl
    #- webserver-setup
