---
- name: Playbook to install and configure troposphere
  hosts: atmosphere
  roles:
    # Dependencies
    - install-dependencies
    - setup-postgres
    - setup-ssl
    
    # Troposphere Portion
    - troposphere-setup-virtualenv
    - troposphere-clone-repo
    - troposphere-setup-troposphere    
