---
- name: Playbook to install and configure troposphere
  hosts: atmosphere
  roles:
    - install-dependencies
    - troposphere-setup-virtualenv
    - setup-postgres
    - troposphere-clone-repo
    - troposphere-setup-troposphere
    - setup-ssl
    #- webserver-setup
