---
- name: Create an Atmosphere and Troposphere stack
  hosts: full_deploy

  roles:
    - { role: print-all-variables,
        tags: ['print-vars'] }


- import_playbook: ./prepare_host.yml
- import_playbook: ./deploy_atmosphere.yml
- import_playbook: ./deploy_troposphere.yml
- import_playbook: ./post_deployment.yml
