---
- name: Setup the Troposphere project
  hosts: all

  roles:

    - { role: app-config-logging,
        APP_BASE_DIR: "{{ TROPOSPHERE_LOCATION }}",
        LOG_FILES: "{{ TROPO_LOG_FILES }}",
        tags: ['troposphere', 'logging']}

    - { role: config-nginx-uwsgi,
        APP_BASE_DIR: "{{ TROPOSPHERE_LOCATION }}",
        UWSGI_APP_NAME: 'troposphere',
        tags: ['troposphere'] }

    - { role: install-airport-ui-assets,
        AIRPORT_SOURCE: "{{ TROPOSPHERE_LOCATION }}",
        tags: ['troposphere', 'airport'] }

    - { role: build-install-troposphere-ui-assets,
        NPM_APP_DIR: "{{ TROPOSPHERE_LOCATION }}",
        NPM_BUILD_TYPE: "{{ TROPOSPHERE_BUILD | default('production') }}",
        tags: ['troposphere', 'npm'] }