---
- name: Setup the Atmosphere API component
  hosts: all

  roles:
    - { role: app-alter-kernel-for-imaging,
        tags: ['atmosphere'] }

    - { role: app-config-postgres,
        DBNAME: "{{ ATMO_DBNAME | default(database_name) }}",
        DBUSER: "{{ ATMO_DBUSER | default(database_user) }}",
        DBPASSWORD: "{{ ATMO_DBPASSWORD | default(database_password) }}",
        tags: ['atmosphere', 'database'] }

    - { role: app-load-data-postgres,
        DBNAME: "{{ ATMO_DBNAME | default(database_name) }}",
        LOAD_DATABASE: "{{ ATMO_DATA.LOAD_DATABASE }}",
        DATABASE_FILE_TO_BE_LOADED: "{{ ATMO_DATA.SQL_DUMP_FILE }}",
        when: "{{ ATMO_DATA is defined and ATMO_DATA.SQL_DUMP_FILE is defined and ATMO_DATA.LOAD_DATABASE }}"
        tags: ['atmosphere', 'data-load'] }

    - { role: delete-files,
        LOCATION: "{{ ATMOSPHERE_LOCATION | default(directory_name) }}",
        GLOB: "*.pyc",
        tags: ['atmosphere'] }

    - { role: app-pip-install-requirements,
        APP_BASE_DIR: "{{ ATMOSPHERE_LOCATION | default(directory_name) }}",
        REQUIREMENTS_FILE_NAME: 'dev_requirements.txt',
        VIRTUAL_ENV: "{{ VIRTUAL_ENV_ATMOSPHERE | default(virtualenv_path) }}",
        PIP_EXTRA_ARGS: '--no-cache-dir',
        tags: ['atmosphere', 'pip-install-requirements']}

    - { role: app-config-logging,
        APP_BASE_DIR: "{{ ATMOSPHERE_LOCATION | default(directory_name) }}",
        LOG_FILES: "{{ ATMO_LOG_FILES }}",
        tags: ['atmosphere', 'logging']}
    # Stopping here for the day. Reminder: We can't shrink variables down until this is dealt with. Tomorrow I will create this nested structure in group_vars..
    - { role: app-generate-ini-config,
        template_vars: "{{ ATMO }}",
        APP_BASE_DIR: "{{ ATMOSPHERE_LOCATION | default(directory_name) }}",
        VIRTUAL_ENV: "{{ VIRTUAL_ENV_ATMOSPHERE | default(virtualenv_path) }}",
        tags: ['atmosphere', 'generate-config'] }

    - { role: app-setup-ssh-keys,
        APP_BASE_DIR: "{{ ATMOSPHERE_LOCATION | default(directory_name) }}",
        CREATE_SSH: "{{ CREATE_SSH_KEYS | default(true) }}",
        SSH_PRIV_KEY: "{{ ID_RSA }}",
        SSH_PUB_KEY: "{{ ID_RSA_PUB }}",
        tags: ['atmosphere', 'ansible-deploy', 'setup-ssh-keys'] }

    - { role: app-install-instance-deploy-automation,
        APP_BASE_DIR: "{{ ATMOSPHERE_LOCATION | default(directory_name) }}",
        INSTANCE_DEPLOY_AUTOMATION_DIR: "{{ ANSIBLE_DEPLOY_LOCATION }}",
        INSTANCE_DEPLOY_AUTOMATION_HOSTS_FILE: "{{ ANSIBLE_HOSTS_FILE }}",
        INSTANCE_DEPLOY_AUTOMATION_GROUP_VARS_FOLDER: "{{ ANSIBLE_GROUP_VARS_FOLDER }}",
        tags: ['atmosphere', 'ansible-deploy'] }

    - { role: app-generate-ini-config,
        template_vars: "{{ ATMOSPHERE_ANSIBLE }}",
        APP_BASE_DIR: "{{ ANSIBLE_DEPLOY_LOCATION }}",
        VIRTUAL_ENV: "{{ VIRTUAL_ENV_ATMOSPHERE | default(virtualenv_path) }}",
        tags: ['atmosphere', 'ansible-deploy'] }

    - { role: app-django-manage-collectstatic,
        APP_BASE_DIR: "{{ ATMOSPHERE_LOCATION | default(directory_name) }}",
        VIRTUAL_ENV: "{{ VIRTUAL_ENV_ATMOSPHERE | default(virtualenv_path) }}",
        DJANGO_SETTINGS_MODULE: 'atmosphere.settings',
        tags: ['atmosphere', 'manage-collectstatic'] }

    - { role: app-django-manage-migrate,
        APP_BASE_DIR: "{{ ATMOSPHERE_LOCATION | default(directory_name) }}",
        VIRTUAL_ENV: "{{ VIRTUAL_ENV_ATMOSPHERE | default(virtualenv_path) }}",
        DJANGO_SETTINGS_MODULE: 'atmosphere.settings',
        tags: ['atmosphere', 'manage-migrate'] }

    - { role: app-django-manage-load-tables,
        APP_BASE_DIR: "{{ ATMOSPHERE_LOCATION | default(directory_name) }}",
        VIRTUAL_ENV: "{{ VIRTUAL_ENV_ATMOSPHERE | default(virtualenv_path) }}",
        DJANGO_SETTINGS_MODULE: 'atmosphere.settings',
        tags: ['atmosphere','manage-load-tables'] }

    - { role: config-nginx-uwsgi,
        APP_BASE_DIR: "{{ ATMOSPHERE_LOCATION | default(directory_name) }}",
        UWSGI_APP_NAME: 'atmosphere',
        UWSGI_INI_SRC_NAME: 'extras/uwsgi/atmo.uwsgi.ini',
        nginx_vars_context: "{{ ATMO['nginx'] }}",
        tags: ['atmosphere', 'deploy', 'nginx-uwsgi'] }

    - { role: setup-webserver-user-group,
        APP_BASE_DIR: "{{ ATMOSPHERE_LOCATION | default(directory_name) }}",
        WEBSERVER_USER: "www-data",
        tags: ['atmosphere','set-permissions'] }

    # The logrotate-files role must come after the setup-webserver-user-group role.
    # This is because setup-webserver-user-group sets the permissions on all files in that directory the
    # to the WEBSERVER_USER user, while logrotate requires root
    - { role: logrotate-files,
        LOGROTATE_FILES: "{{ ATMOSPHERE_LOCATION | default(directory_name) }}/extras/logrotate.atmosphere",
        tags: ['atmosphere', 'logrotate'] }
