- name: Stat to see if item.src_path is on host machine
  local_action: stat path="{{item.src_path}}"
  register: local_file

- name: Copy certificate from host to target destination
  copy: content="{{ lookup('file', item.src_path) }}\r\n" dest="{{ item.dest_path }}"
  when: local_file.stat.exists

- name: Copy certificate from target to destination
  shell: "cp {{ item.src_path }} {{ item.dest_path }}"
  when: not local_file.stat.exists
